projeto_process/cadastro/urls.py
from django.urls import path

from .views import ProcessosICreate, FonteICreate,PaoeICreate,BBMICreate,ElementoICreate
from .views import ProcessosIUpdate, FonteIUpdate, PaoeIUpdate,BBMIUpdate,ElementoIUpdate
from .views import ProcessosIDelete, FonteIDelete, PaoeIDelete,BBMIDelete,ElementoIDelete
from .views import ProcessosList, FonteList, PaoeList,BBMList,ElementoList

# ----- Neste arquivo são deferidas as URLs que serão utilizadas nesta pasta, todas elas serão puxadas pela pasta do app principal no arquivo "configurações/urls.py". ----- 

# Colocar nessa variavel todos os teamplates que poderão ser chamados pela URL
urlpatterns = [
    
    #definindo como chamar cada página na URL

    # ---- CRIAÇÃO ---- #
    path('cadastrar/processo/', ProcessosICreate.as_view(), name='cadastrar-processo'),
    path('cadastrar/fonte/', FonteICreate.as_view(), name='cadastrar-fonte'),
    path('cadastrar/paoe/', PaoeICreate.as_view(), name='cadastrar-paoe'),
    path('cadastrar/bbm/', BBMICreate.as_view(), name='cadastrar-bbm'),
    path('cadastrar/elemento/', ElementoICreate.as_view(), name='cadastrar-elemento'),
    

    # ---- EDIÇÃO ---- #
    #int(inteiro), pk(primarykey) - pk é o id do objeto
    path('editar/processo/<int:pk>/', ProcessosIUpdate.as_view(), name='editar-processo'),
    path('editar/fonte/<int:pk>/', FonteIUpdate.as_view(), name='editar-fonte'),
    path('editar/paoe/<int:pk>/', PaoeIUpdate.as_view(), name='editar-paoe'),
    path('editar/bbm/<int:pk>/', BBMIUpdate.as_view(), name='editar-bbm'),
    path('editar/bbm/<int:pk>/', BBMIUpdate.as_view(), name='editar-bbm'),
     path('editar/elemento/<int:pk>/', ElementoIUpdate.as_view(), name='editar-elemento'),


    # ---- EXCLUSÃO ---- #
    path('excluir/processo/<int:pk>/', ProcessosIDelete.as_view(), name='excluir-processo'),
    path('excluir/fonte/<int:pk>/', FonteIDelete.as_view(), name='excluir-fonte'),
    path('excluir/paoe/<int:pk>/', PaoeIDelete.as_view(), name='excluir-paoe'),
    path('excluir/bbm/<int:pk>/', BBMIDelete.as_view(), name='excluir-bbm'),
    path('excluir/elemento/<int:pk>/', ElementoIDelete.as_view(), name='excluir-elemento'),

    # ---- LISTAS ---- #
    path('lista/processo/', ProcessosList.as_view(), name='listar-processo'),
    path('lista/fonte/', FonteList.as_view(), name='listar-fonte'),
    path('lista/paoe/', PaoeList.as_view(), name='listar-paoe'),
    path('lista/bbm/', BBMList.as_view(), name='listar-bbm'),
    path('lista/elemento/', ElementoList.as_view(), name='listar-elemento'),



]

projeto_process/cadastro/models.py
from django.db import models
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.models import User





# Aqui criamos as classes que serão alocadas no sqlite3 e que também será chamado na página views para a definição das entrys e etc.


#essa classe foi usada como exemplo
#     
class Fonte(models.Model):
    fonte = models.DecimalField(verbose_name="Fonte", max_digits=3, decimal_places=0)
    desc_fonte = models.CharField(max_length=150, verbose_name="Descrição da fonte" )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['fonte'], name='fonte repetida')
        ] 

    #Retorna a representação em STRING do objeto
    def __str__(self):
        return "{} ({})".format(self.fonte, self.desc_fonte)
    
class Paoe(models.Model):
    paoe = models.CharField(verbose_name="PAOE", max_length=150)
    desc_paoe = models.CharField(max_length=150, verbose_name="Descrição da PAOE" )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['paoe'], name='paoe repetida')
        ]

    #Retorna a representação em STRING do objeto
    def __str__(self):
        return "{} ({}) ".format(self.paoe, self.desc_paoe)   
    
class BBM(models.Model):
    desc_unidade = models.CharField(max_length=50, verbose_name="Descrição da Unidade", default="",help_text='Nome por extenso da unidade.')
    sigla_unidade = models.CharField(max_length=12, verbose_name="Sigla da Unidade", help_text='Exemplo: <strong>SCG</strong>.')

    localidade = models.CharField(max_length=30, verbose_name="Município", help_text="Localidade em que a UBM está situada.")

    def __str__(self):
        return "{} ({}) ".format(self.sigla_unidade, self.localidade)  

class Elemento(models.Model):
    
    elemento = models.CharField(max_length=30, verbose_name="Elemento")
    desc_elemento = models.CharField(max_length=250, verbose_name="Descrição do elemento")

    def __str__(self):
        return "{} ({}) ".format(self.elemento, self.desc_elemento)  

class UnidadeGestora(models.Model):
    gestora = models.ForeignKey(BBM, on_delete=models.PROTECT, verbose_name="Nome da Gestora:", null=True)
    numero_ug = models.IntegerField(verbose_name="Número da UG", null=True)
    def __str__(self):
            return "{} - UG({})".format(self.gestora.sigla_unidade, self.numero_ug)

class Processos(models.Model):
    
    processo = models.CharField(max_length=150, verbose_name="Nº do Processo SEi")
    bbm2 = models.ForeignKey(BBM, on_delete=models.PROTECT, verbose_name="OBM")
    fonte2 = models.ForeignKey(Fonte, on_delete=models.PROTECT, verbose_name="Fonte")
    paoe2 = models.ForeignKey(Paoe, on_delete=models.PROTECT, verbose_name="PAOE")
    elemento2 = models.ForeignKey(Elemento, on_delete=models.PROTECT, verbose_name="Elemento", blank=True, null=True)
    ug = models.ForeignKey(UnidadeGestora, on_delete=models.PROTECT, verbose_name="Unidade Geradora",null=True,blank=True)
    data_da_solicitacao = models.DateField(verbose_name="Data da Solicitação")  
    valor_solicitado = models.CharField(max_length=2000, verbose_name="Valor Solicitado", default="R$0,00", blank=True, null=True,unique=True)
    
    descricao = models.CharField(max_length=150, verbose_name="Descrição")
    # contrato = models.CharField(max_length=150, verbose_name="Contrato", blank=True, null=True)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT,)
    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(fields=['processo', 'data_da_indicação','fonte2','paoe2','bbm2'], name='processo do ano')
    #     ]

    #Retorna a representação em STRING do objeto
    def __str__(self):
        return "{} - Fonte({}) {} - {}".format(self.bbm2, self.fonte2.fonte, self.paoe2, self.descricao)

projeto_process/cadastro/templates/cadastros/form-excluir.html
{% extends 'paginas/modelo.html' %}

<!-- carregando os modelos estáticos -->
{% load static %}


{% load crispy_forms_tags %}



<!-- página criada automaticamente apartir da .view (do proprio django), carregando um modelo pré definido -->

{% block conteudo %}
<div class='container'> 
    <hr>
    <h3>Excluir Registros</h3>
    <hr>
    <p class="lead">
        Confirme para excluir o registro definitivamente
    </p>

    

    <form action="" method="post">
        
        <p>
            Deseja excluir o registro : <strong>{{ object }}</strong>?
        </p>
        {% csrf_token %}

        {{ form|crispy }}
        
        <a href="javascript:history.back()" class="btn btn-primary" title="Cancelar" aria-hidden="true">Cancelar</a>
        <button type="submit" class="btn btn-danger" title="Excluir">Excluir</button>
        


    </form>

</div>

{% endblock %}

projeto_process/cadastro/templates/cadastros/form.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% load crispy_forms_tags %}


{% block conteudo %}


<div class='container border rounded jumbotron mx-auto px-4 m-3 bg-light text-dark'>   
    <h3 class="my-4">Cadastrar Registros</h3>
    <hr>
    <div class="container p-3">
        
        <form action="" method="POST" class="form-inline mx-auto">
            <!-- chamada do django para verificação segura -->
                
            {% csrf_token %}

            <!-- chamada do django que transforma o form em paragrafo -->
            {{ form|crispy }}
                
            <br><button type="submit" class="btn btn-primary mg-2 p-2">Cadastrar</button>
            
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="{% static 'js/jquery.maskMoney.min.js' %}"></script>
<script>
// jquery formatando máscaras
    $(document).ready(function(){
        $("#id_data_da_indicação").mask("00/00/0000",  {placeholder: "dd/mm/aaaa"});
        
        $('#id_valor_ind').maskMoney({
            prefix:'R$',
            allowNegative: true,
            thousands:'.', 
            decimal:',',
            affixesStay:true});
        
        $('#id_valor_solicitado_ind').maskMoney({
            prefix:'R$',
            allowNegative: true,
            thousands:'.', 
            decimal:',',
            affixesStay:true});
        });
</script>



{% endblock %}

projeto_process/cadastro/templates/cadastros/form_processo.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% load crispy_forms_tags %}


{% block conteudo %}


<div class='container border rounded jumbotron mx-auto px-4 m-4 bg-light text-dark'>   
    <h3 class="my-4">Cadastrar Registros</h3>
    <hr>
    
    
    <!-- Form de confirmação de exclusão -->
    <div class="gap-2 d-md-flex justify-content-md-end">
        <p class="lead col">Preencha todos os campos obrigatórios:</p>
        <input type="checkbox" class="btn-check " id="btncheck1" autocomplete="off"/>
        <label class="btn btn-outline-danger p-2 lg-2"  for="btncheck1">Exceção</label>
            
    </div>
    <div class="container">
        <div class="row align-items-start">
           <div class="col"> 
                    <form action="" method="POST" class=" form-group mb-2">
                    
                    <!-- chamada do django para verificação segura -->
                        
                    {% csrf_token %}
                    
                    {{ form|crispy }}
                    
                    <!-- chamada do django que transforma o form em paragrafo -->
                    <div class="p-2 m-1">
                        <!-- <button type="button" class="btn btn-success px-3 ">+</button>  -->
                        <button type="submit" class="btn btn-primary  px-2">Cadastrar</button> 
                    </div>
                </form>
            </div>
            
            <!-- Colocar aqui a parte da descentralização -->
            <div class="col">
                <form class="fomr-inline form-borderd" action="">   

                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="{% static 'js/jquery.maskMoney.min.js' %}"></script>
<script>
// jquery formatando máscaras
    $(document).ready(function(){
       
        
        $('#id_valor_solicitado').maskMoney({
            prefix:'R$',
            allowNegative: true,
            thousands:'.', 
            decimal:',',
            affixesStay:true});
        });
</script>



{% endblock %}